---
title: Kloppend hart
hero_image: images/banner.png
description:
  - Maak een papieren hart dat klopt met een potentiometer om een LED te besturen
  - dat knippert als een hartslag
meta_title: Raspberry Pi Pico projects | Beating heart
meta_description: A Raspberry Pi Pico project to make a papercraft beating heart with a pulsing LED and a dial to adjust the heart rate.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Lees waarden van een instelwiel
  - 
    title: Bereken slagen per minuut (BPM)
    completion:
      - engaged
  - 
    title: Maak een papieren hart
  - 
    title: LED-hartslag
  - 
    title: Maak het draagbaar
    completion:
      - internal
  - 
    title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
