title: Beating heart
hero_image: images/banner.png
description: Make a papercraft beating heart with a button to control an LED that blinks like a heartbeat. 
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Read values from a dial
  - title: Calculate beats per minute (BPM)
    completion: engaged
  - title: Control the LED with a button
  - title: Make a Papercraft heart
    completion: internal
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion: external
  - title: Upgrade your project
  - title: What next?
