---
title: Bultande hjärta
hero_image: images/banner.png
description:
  - Gör ett hjärta i papper som slår, med en potentiometer för att styra en lysdiod
  - som blinkar som ett hjärtslag
meta_title: Raspberry Pi Pico-projekt | Bultande hjärta
meta_description: Ett Raspberry Pi Pico-projekt för att göra ett hjärta i papper som slår, med en pulserande LED och en ratt för att justera pulsen.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Du kommer att göra
  - 
    title: Läs värden från en ratt
  - 
    title: Beräkna slag per minut (BPM)
    completion:
      - engaged
  - 
    title: Gör ett pappershjärta
  - 
    title: Lysdiod-hjärtslag
  - 
    title: Gör den portabel
    completion:
      - internal
  - 
    title: Snabbt quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Uppgradera ditt projekt
  - 
    title: Vad härnäst?
