---
title: Καρδιά που χτυπά
hero_image: images/banner.png
description:
  - Φτιάξε μια χάρτινη καρδιά που χτυπά με ένα ποτενσιόμετρο για να ελέγχεις ένα LED
  - που αναβοσβήνει σαν καρδιοχτύπι
meta_title: Έργα Raspberry Pi Pico | Καρδιά που χτυπά
meta_description: Ένα έργο Raspberry Pi Pico για την κατασκευή μιας χάρτινης καρδιάς που χτυπά με ένα παλλόμενο LED και έναν επιλογέα για τη ρύθμιση του καρδιακού ρυθμού.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Τι θα φτιάξεις
  - 
    title: Ανάγνωση τιμών από έναν επιλογέα
  - 
    title: Υπολογισμός παλμών ανά λεπτό (BPM)
    completion:
      - engaged
  - 
    title: Φτιάξτε μια καρδιά από χαρτί
  - 
    title: Χτύπος καρδιάς LED
  - 
    title: Κάνε το φορητό
    completion:
      - internal
  - 
    title: Γρήγορο κουίζ
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Αναβάθμιση του έργου σου
